/** @type {import('tailwindcss').Config} */
export default {
	content: [
		"./index.html",
		"./src/**/*.{js,ts,jsx,tsx}",
	],
	theme: {
		extend: {
			colors: {
				"on-tertiary-container": "#4d3500",
				"on-surface-variant": "#c0c7d4",
				"primary-fixed-dim": "#a2c9ff",
				"on-surface": "#dae3ee",
				"surface-variant": "#2d363e",
				"outline-variant": "#414752",
				"on-secondary-container": "#91f294",
				"surface-container-lowest": "#060f16",
				"on-secondary-fixed-variant": "#005319",
				"surface-container-low": "#141c24",
				"surface-bright": "#313a43",
				"on-error-container": "#ffdad6",
				"tertiary-container": "#d29922",
				"surface": "#0b141c",
				"surface-container": "#182028",
				"secondary": "#7bdb80",
				"on-primary-fixed-variant": "#004882",
				"tertiary": "#fabc45",
				"surface-container-highest": "#2d363e",
				"inverse-on-surface": "#29313a",
				"on-tertiary-fixed": "#271900",
				"surface-dim": "#0b141c",
				"tertiary-fixed-dim": "#fabc45",
				"primary-fixed": "#d3e4ff",
				"secondary-container": "#007124",
				"on-primary-container": "#003a6b",
				"on-tertiary": "#422c00",
				"secondary-fixed": "#97f999",
				"primary": "#a2c9ff",
				"background": "#0b141c",
				"on-error": "#690005",
				"on-secondary-fixed": "#002106",
				"on-tertiary-fixed-variant": "#5f4100",
				"on-primary": "#00315c",
				"surface-tint": "#a2c9ff",
				"outline": "#8b919d",
				"inverse-primary": "#0060aa",
				"error": "#ffb4ab",
				"tertiary-fixed": "#ffdeaa",
				"surface-container-high": "#222b33",
				"error-container": "#93000a",
				"secondary-fixed-dim": "#7bdb80",
				"on-secondary": "#00390e",
				"primary-container": "#58a6ff",
				"inverse-surface": "#dae3ee",
				"on-primary-fixed": "#001c38",
				"on-background": "#dae3ee"
			},
			borderRadius: {
				"DEFAULT": "0.125rem",
				"lg": "0.25rem",
				"xl": "0.5rem",
				"full": "0.75rem"
			},
			spacing: {
				"unit": "4px",
				"margin-desktop": "24px",
				"margin-mobile": "16px",
				"panel-sidebar": "260px",
				"gutter": "16px",
				"panel-toolbar": "48px"
			},
			fontFamily: {
				"body-md": ["Geist", "sans-serif"],
				"code-md": ["JetBrains Mono", "monospace"],
				"label-sm": ["Geist", "sans-serif"],
				"headline-lg": ["Geist", "sans-serif"],
				"headline-md": ["Geist", "sans-serif"],
				"body-lg": ["Geist", "sans-serif"]
			},
			fontSize: {
				"body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
				"code-md": ["14px", { "lineHeight": "22px", "fontWeight": "400" }],
				"label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
				"headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
				"headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
				"body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
			}
		},
	},
	plugins: [],
}